language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

git:
  depth: 1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env: DEFAULT_COMPOSER_FLAGS="--optimize-autoloader --no-interaction"

before_install:
  # Composer: boost installation
  - composer global show hirak/prestissimo -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

install:
  # install dependencies
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist $DEFAULT_COMPOSER_FLAGS

script:
  - composer validate --no-check-lock
  - composer test
